version: '3.8'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    ports:
      - "127.0.0.1:8545:8545"
    volumes:
      - .:/app:ro
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - HARDHAT_NETWORK=localhost
    command: pnpm node
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          memory: 512M
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8545"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "10"
    networks:
      - blockchain-net

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    networks:
      - blockchain-net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - blockchain-net
    depends_on:
      - prometheus

networks:
  blockchain-net:
    driver: bridge
    internal: true

volumes:
  node_modules:
  grafana-storage:
